# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0d4f0312fe59201fe3712edf0e896692791cb13773d4c461c8d60012db07d52a17ff1a325d90b471b8d1d338e5ef88042d4bd754d4f11ffb1e502263362c7305

test:
  secret_key_base: c80975541e289b2e144ade6bf52c9b60a8484699205cf7fc755b61f9529111c3a98fa88e6425642a63bf3759811c7755523b2781d7403b264638dd51c9a685c1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
